// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZNESc9Xi5RiO8CAUSYss8Xw-hvZ5OTL4',
    appId: '1:355358535933:web:74c40c54bfe5c14449ce94',
    messagingSenderId: '355358535933',
    projectId: 'fir-basics-e93fb',
    authDomain: 'fir-basics-e93fb.firebaseapp.com',
    storageBucket: 'fir-basics-e93fb.appspot.com',
    measurementId: 'G-M7HJLB18D1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALlqhWFY39PNzxTVJEJuf0tu__VwRgdlk',
    appId: '1:355358535933:android:9c2f9a444d9e0c4c49ce94',
    messagingSenderId: '355358535933',
    projectId: 'fir-basics-e93fb',
    storageBucket: 'fir-basics-e93fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2QHcgaPU1f3myYIvelAdexld4WyxZoFg',
    appId: '1:355358535933:ios:1b70f37eb2a24d9749ce94',
    messagingSenderId: '355358535933',
    projectId: 'fir-basics-e93fb',
    storageBucket: 'fir-basics-e93fb.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2QHcgaPU1f3myYIvelAdexld4WyxZoFg',
    appId: '1:355358535933:ios:103303c244f4e8b649ce94',
    messagingSenderId: '355358535933',
    projectId: 'fir-basics-e93fb',
    storageBucket: 'fir-basics-e93fb.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseBasics.RunnerTests',
  );
}
